/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.LivrosDAO;
import MODEL.LivrosMODEL;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PuddinAPX
 */
public class LivrosVIEW extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form LivrosVIEW
     */
    public LivrosVIEW() {
        initComponents();
        listarlivros();
        JButton [] btns = {btnHOME,btnLIVRO,btnCADASTRO,btnEMPRESTIMO, btnDEVOLUCAO};
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        for (JButton btn : btns){
            btn.setBackground(new Color (0,0,0));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {
                    }

                @Override
                public void mousePressed(MouseEvent me) {
                    }

                

                @Override
                public void mouseEntered(MouseEvent me) {
                    btn.setBackground(new Color(28,28,28));
                    }

                @Override
                public void mouseExited(MouseEvent me) {
                    btn.setBackground(new Color(0,0,0));
                    }

                @Override
                public void mouseReleased(MouseEvent me) {
                    }
            });
        }
        btnDEVOLUCAO.addActionListener((e)->{
            this.setVisible(false);
            new DevolucaoVIEW();
        });
        btnEMPRESTIMO.addActionListener((e)->{
            this.setVisible(false);
            new EmprestimoVIEW();
        });
        btnCADASTRO.addActionListener((e)->{
            this.setVisible(false);
            new CadastroVIEW();
        });
        btnHOME.addActionListener((e)->{
            this.setVisible(false);
            new HomeVIEW();
        });
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHOME = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLIVRO = new javax.swing.JButton();
        btnCADASTRO = new javax.swing.JButton();
        btnEMPRESTIMO = new javax.swing.JButton();
        btnDEVOLUCAO = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnEDITAR = new javax.swing.JButton();
        btnATUALIZAR = new javax.swing.JButton();
        btnEXCLUIR = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnHOME.setBackground(new java.awt.Color(0, 0, 0));
        btnHOME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icons/pinguin.png (2).png"))); // NOI18N
        btnHOME.setBorder(null);
        btnHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHOMEActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIBLIOTECH");

        btnLIVRO.setBackground(new java.awt.Color(0, 0, 0));
        btnLIVRO.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLIVRO.setForeground(new java.awt.Color(255, 255, 255));
        btnLIVRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icons/livro.png"))); // NOI18N
        btnLIVRO.setText("  Livros");
        btnLIVRO.setBorder(null);
        btnLIVRO.setPreferredSize(new java.awt.Dimension(57, 50));
        btnLIVRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIVROActionPerformed(evt);
            }
        });

        btnCADASTRO.setBackground(new java.awt.Color(0, 0, 0));
        btnCADASTRO.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCADASTRO.setForeground(new java.awt.Color(255, 255, 255));
        btnCADASTRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icons/conecte-se (1) (1).png"))); // NOI18N
        btnCADASTRO.setText("Cadastrar");
        btnCADASTRO.setBorder(null);
        btnCADASTRO.setPreferredSize(new java.awt.Dimension(57, 50));
        btnCADASTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCADASTROActionPerformed(evt);
            }
        });

        btnEMPRESTIMO.setBackground(new java.awt.Color(0, 0, 0));
        btnEMPRESTIMO.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEMPRESTIMO.setForeground(new java.awt.Color(255, 255, 255));
        btnEMPRESTIMO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icons/emprestimo.png"))); // NOI18N
        btnEMPRESTIMO.setText("Emprestar");
        btnEMPRESTIMO.setBorder(null);
        btnEMPRESTIMO.setPreferredSize(new java.awt.Dimension(57, 50));
        btnEMPRESTIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMPRESTIMOActionPerformed(evt);
            }
        });

        btnDEVOLUCAO.setBackground(new java.awt.Color(0, 0, 0));
        btnDEVOLUCAO.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDEVOLUCAO.setForeground(new java.awt.Color(255, 255, 255));
        btnDEVOLUCAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icons/devolucao.png"))); // NOI18N
        btnDEVOLUCAO.setText(" Devolver");
        btnDEVOLUCAO.setBorder(null);
        btnDEVOLUCAO.setPreferredSize(new java.awt.Dimension(57, 50));
        btnDEVOLUCAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDEVOLUCAOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLIVRO, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEMPRESTIMO, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDEVOLUCAO, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHOME, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHOME))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)))
                .addGap(41, 41, 41)
                .addComponent(btnCADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEMPRESTIMO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDEVOLUCAO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLIVRO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaLivros.setBackground(new java.awt.Color(255, 255, 255));
        tabelaLivros.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tabelaLivros.setForeground(new java.awt.Color(0, 0, 0));
        tabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "LIVRO", "EDITORA", "AUTOR", "CATEGORIA", "STATUS", "R$", "ANO ", "COD."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaLivros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaLivros.setGridColor(new java.awt.Color(0, 0, 0));
        tabelaLivros.setRowHeight(40);
        tabelaLivros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaLivros);
        if (tabelaLivros.getColumnModel().getColumnCount() > 0) {
            tabelaLivros.getColumnModel().getColumn(0).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(0).setPreferredWidth(3);
            tabelaLivros.getColumnModel().getColumn(1).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabelaLivros.getColumnModel().getColumn(2).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(2).setPreferredWidth(50);
            tabelaLivros.getColumnModel().getColumn(3).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabelaLivros.getColumnModel().getColumn(4).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(4).setPreferredWidth(80);
            tabelaLivros.getColumnModel().getColumn(5).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(5).setPreferredWidth(50);
            tabelaLivros.getColumnModel().getColumn(6).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(6).setPreferredWidth(20);
            tabelaLivros.getColumnModel().getColumn(7).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(7).setPreferredWidth(20);
            tabelaLivros.getColumnModel().getColumn(8).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(8).setPreferredWidth(60);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 940, 500));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 10));

        btnEDITAR.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icons/botao-editar (1).png"))); // NOI18N
        btnEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDITARActionPerformed(evt);
            }
        });
        jPanel2.add(btnEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, -1));

        btnATUALIZAR.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnATUALIZAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icons/refrescar (1).png"))); // NOI18N
        btnATUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnATUALIZARActionPerformed(evt);
            }
        });
        jPanel2.add(btnATUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 90, -1));

        btnEXCLUIR.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnEXCLUIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icons/excluir (1).png"))); // NOI18N
        btnEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXCLUIRActionPerformed(evt);
            }
        });
        jPanel2.add(btnEXCLUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 90, -1));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setBorder(null);
        txtID.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtID.setEnabled(false);
        txtID.setOpaque(false);
        txtID.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 40, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total Disponiveis", "Total Emprestados" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 250, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 940, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHOMEActionPerformed

    private void btnLIVROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIVROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLIVROActionPerformed

    private void btnCADASTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCADASTROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCADASTROActionPerformed

    private void btnEMPRESTIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMPRESTIMOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEMPRESTIMOActionPerformed

    private void btnDEVOLUCAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDEVOLUCAOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDEVOLUCAOActionPerformed

    private void btnATUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnATUALIZARActionPerformed
        listarlivros();
    }//GEN-LAST:event_btnATUALIZARActionPerformed

    private void btnEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDITARActionPerformed
        Editar();
    }//GEN-LAST:event_btnEDITARActionPerformed

    private void btnEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXCLUIRActionPerformed
        Excluir();
        listarlivros();
    }//GEN-LAST:event_btnEXCLUIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivrosVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnATUALIZAR;
    private javax.swing.JButton btnCADASTRO;
    private javax.swing.JButton btnDEVOLUCAO;
    private javax.swing.JButton btnEDITAR;
    private javax.swing.JButton btnEMPRESTIMO;
    private javax.swing.JButton btnEXCLUIR;
    private javax.swing.JButton btnHOME;
    private javax.swing.JButton btnLIVRO;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    protected javax.swing.JTable tabelaLivros;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        this.setVisible(false);
        new HomeVIEW();
    }
    
    public void listarlivros(){
        try {
            LivrosDAO objlivrosD = new LivrosDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaLivros.getModel();
            model.setNumRows(0);
            
            ArrayList<LivrosMODEL> lista = objlivrosD.listarLivros();
            
            for(int num = 0; num < lista.size(); num++){
                model.addRow(new Object[]{
                    lista.get(num).getId_livros(),
                    lista.get(num).getNome_livro(),
                    lista.get(num).getEditora(),
                    lista.get(num).getAutor(),
                    lista.get(num).getCategoria(),
                    lista.get(num).getStatus_livro(),
                    lista.get(num).getValor_livro(),
                    lista.get(num).getAno_lancamento(),
                    lista.get(num).getCod_livro()
                });
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarLivros VIEW: " + erro);
        }
    }
    
    
    public void Editar(){
        int setar = tabelaLivros.getSelectedRow();
        
        if(tabelaLivros.getSelectedRow() != -1){
        EditarLivroVIEW objLivroVE = new EditarLivroVIEW();  
        objLivroVE.setVisible(true);
        
        objLivroVE.txtID.setText(tabelaLivros.getModel().getValueAt(setar, 0).toString());
        objLivroVE.txtNome.setText(tabelaLivros.getModel().getValueAt(setar, 1).toString());
        objLivroVE.txtEditora.setText(tabelaLivros.getModel().getValueAt(setar, 2).toString());
        objLivroVE.txtAutor.setText(tabelaLivros.getModel().getValueAt(setar, 3).toString());
        objLivroVE.txtCategoria.setText(tabelaLivros.getModel().getValueAt(setar, 4).toString());
        objLivroVE.txtValor.setText(tabelaLivros.getModel().getValueAt(setar,6).toString());
        objLivroVE.txtAno.setText(tabelaLivros.getModel().getValueAt(setar, 7).toString());
        objLivroVE.txtCodlivro.setText(tabelaLivros.getModel().getValueAt(setar, 8).toString());
        
        }
        
    }
    
    public void Excluir(){
        int id_livro;
        
        int setar = tabelaLivros.getSelectedRow();
        
        if(tabelaLivros.getSelectedRow() != -1){
            
        txtID.setText(tabelaLivros.getModel().getValueAt(setar, 0).toString());
        
        id_livro = Integer.parseInt(txtID.getText());
        
        LivrosMODEL objlivrosM = new LivrosMODEL();
        objlivrosM.setId_livros(id_livro);
        
        LivrosDAO objlivrosD = new LivrosDAO();
        objlivrosD.ExcluirLivro(objlivrosM);
        
        
       }
    }
    
}
